<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="RunCompsition" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://j2ee.netbeans.org/wsdl/CompositeService/CompositeServiceWSDL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="RunCompsition" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://j2ee.netbeans.org/wsdl/CompositeService/CompositeServiceWSDL" location="http://192.168.1.107:9080/RunCompsition-sun-http-binding/CompositeService/CompositeServiceWSDL.wsdl">
    </import>
  <portType name="dummyCasaPortType">
  </portType>
  <binding name="casaBinding1" type="ns:CompositeServiceWSDLPortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ReservationOperation">
      <soap:operation/>
      <input name="input1">
        <soap:body use="literal" namespace="RunCompsition"/>
      </input>
      <output name="output1">
        <soap:body use="literal" namespace="RunCompsition"/>
      </output>
    </operation>
  </binding>
  <service name="RunCompsitionService1">
    <port name="casaPort1" binding="tns:casaBinding1">
      <soap:address location="http://192.168.1.107:9080/RunCompsitionService1/casaPort1"/>
    </port>
  </service>
</definitions>
